image: node:9.0.0

stages:
  - ver
  - init
  - tests
  - deploy

ver:
  stage: ver
  script:
    - node --version
    - whoami
init:
  stage: init
  script:
    - npm cache clean
    - rm -rf node-modules
    - npm install
run_tests:
  stage: tests
  script:
    - npm test

deploy_staging:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/skillshape2.git
    - git push heroku master
    - echo "Deployed to staging server"
  environment:
  name: staging
  url: https://text-giving-staging.herokuapp.com/
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/skillshape2.git
    - git push heroku master
    - echo "Deployed to production server"
  environment:
  name: production
  url: https://skillshape2.herokuapp.com/
  when: manual
  only:
    - master