export default (_skillCategoryObj = {
  "Martial Art": ["Aikido", "American Karate", "American Kenpo", "Arnis/Eskrima/Kali", "Boxing", "Brazilian jiu-jitsu", "Capoeira", "Daitō-ryū Aiki-jūjutsu", "Danzan-ryū", "Fencing", "Hapkido", "Iaido", "Japanese Jujitsu", "Japanese Karate", "Japnese KenPo", "Jeet Kune Do", "Judo", "BoJutsu", "Jujutsu", "Kajukenbo", "Kalaripayattu", "Karate", "Kendo", "Kendo", "Kenjutsu", "KenJutsu", "Wing Chun", "Kenpo", "Kick Boxing", "Krav Maga", "Kung Fu", "Mixed Martial Arts MMA", "Muay Thai", "Ninjutsu", "Nippon Kempo", "Okinawan martial arts", "Olympic Wrestling", "Other Traditional Martial Art", "Pankration", "Sambo", "Savate", "SCA", "Shootfighting (American)", "Shorinji Kempo", "Small Circle Jujutsu", "Sumo", "Systema", "Tai chi chuan", "Taekwondo", "Vale Tudo", "WuShu",],
  " Dance": ["African", "Argentine tango", "B-boying", "Ballet", "Ballroom dance", "Belly dance", "Bounce", "Break Dancing", "Cha Cha", "Charleston", "Classical Indian dance", "Concert dance", "Contact improvisation", "Contemporary dance", "Disco / electronic dance", "East Coast Swing", "Ethnic dance", "Experimental / freestyle", "Flamenco", "Flexing", "Floating", "Folk dance", "Footwork", "Foxtrot", "Hip Hop / Street Dance", "Hula", "Jazz dance", "Jitterbug", "Krumping", "Locking", "Maculelê", "Mambo", "Medieval dance", "Merengue", "Metal Mosh", "Modern dance", "Pole dance", "Quickstep", "Reggaeton", "Robot dance", "Rumba", "Salsa", "Samba", "Swing dance", "Tango", "Tap dance", "Vogue", "Waltz", "Zumba", "Other / Various Dance Styles",],
  "Art/ Design/Craft": ["Acrylic Painting", "Cartoon Art", "Crafting", "Creative Writing", "Crocheting", "Drawing", "Figure Drawing", "Fingernail Art", "Graphic Design", "Hair Styling", "Knitting", "Makeup", "Oil Paint", "Sculpture", "Sewing", "Soap / Cosmetic", "Stitching", "Watercolor", "Painting", "Various Arts", "Grafitti", "Fine Arts", "Ceramic Arts", "Metal Work", "Glasswork", "Other /Various Art / Design/ Craft",],
  "Sport/Exercise": ["Acrobatics", "American Football", "Barre", "Baseball", "Basketball", "Boot Camp", "Cycling", "Darts", "Football / Soccer", "Frisbee", "Gymnastics", "High Intensity Interval Training", "Jogging", "Juggling", "Other Sport/ Exercise", "Parkour", "Pilates", "Racketball", "Rugby", "Sprinting", "Surfing", "Swimming", "Tai Chi", "Tennis", "Ultimate Frisbee", "Walking", "Weight / Resistance", "Windsurfing", "Water-skiing", "Wakeboarding", "Waterski", "Standup paddle boarding",],
  "Language": ["Arabic", "Bengali", "Dutch", "English", "French", "German", "Hindi", "Italian", "Japanese", "Mandarin", "Portuguese", "Russian", "Spanish", "Other Language",],
  "Coding and Computers": ["Android", "C#", "C+", "iOS", "Javascript", "Java", "Meteor", "Node", "PHP", "Python", "Ruby on Rails", "HTML", "CSS", "Wordpress", "Other / Various Code Language",],
  "Business/ Marketing": ["Accounting", "Business Strategy", "Business Writing", "Entrepreneurship", "Marketing", "Sales", "Other / Various Business Skills",],
  "Meditation/ Spirituality/ Religion": ["Bible Study", "Buddhist Chanting", "Catholic Prayer Meeting", "Christian Meeting", "Koran Study", "Meditation", "Muslim Prayer Meeting", "Protestant Prayer Meeting", "Sutra Study", "Other / Various Spirituality/ Religion",],
  "Acting/ Comedy": ["Acting Class", "Improvisation", "Stand-Up Comedy", "Movement / Slapstick", "Method Acting", "Theatre Acting", "Screen Acting", "Other / Various Acting Styles",],
  "Games": ["Video Games", "Role Playing Games", "Miniature Games", "Chess", "Checkers", "Poker", "Board Games", "Card Games", "Other / Various Games",],
  "Pets": ["Dog Walks", "Dog Grooming", "Dog Meetups", "Exotic Pet Meetups", "Dog Training", "Other / Various Pet Activity",],
  "Parents/Children": ["Child Meetup by Age", "Parents with Autistic Children", "Parents with Special Needs Children", "Other / Various Parenting Activity",],
  "Yoga": ["Anusara", "Ashtanga", "Bikram", "Hatha", "Hot Yoga", "Iyengar", "Jivamukti", "Kripalu", "Kundalini", "Prenatal", "Restorative", "Sivananda", "Viniyoga", "Vinyasa / Power", "Yin Yoga", "Health Yoga", "Other / Various Yoga",],
  "Food and Beverage": ["Beer Making", "Bread Making", "Cocktail Mixing", "Cooking", "Fermentation", "Wine Tasting", "Other / Various Food / Beverage",],
  "Life Skills": ["Bullying Prevention", "Coping", "Emotional Intelligence", "Leadership", "Reading/ Literacy", "Vocational Skills", "Conflict Resolution / Mediation", "Other / Various Life Skills",],
  "Music": ["Percussion", "Drums", "Bass", "Production", "DJing", "Guitar Electric", "Guitar Classical", "Guitar Rhythm", "Singing", "Band", "Wind Instrument", "Other Instrument", "Guitar ", "Keyboard", "Piano", "Other / Various Music Activity",],
  "Other": ["Other",],
});


